" Matugen colorscheme — auto-generated by matugen, do not hand-edit
" Colors come from Material You palette derived from your wallpaper.
" Re-run matugen to update after changing wallpaper.

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "matugen"

" ── Terminal ANSI palette (mirrors ghostty/kitty template) ──────────────────
" 0  surface_container_high  (black)
" 1  error                   (red)
" 2  primary                 (green)
" 3  tertiary                (yellow)
" 4  secondary               (blue)
" 5  primary_fixed           (magenta)
" 6  secondary_fixed         (cyan)
" 7  on_surface_variant      (white)
" 8  outline                 (bright black)
" 9  error_container         (bright red)
" 10 primary_container       (bright green)
" 11 tertiary_container      (bright yellow)
" 12 secondary_container     (bright blue)
" 13 inverse_primary         (bright magenta)
" 14 outline_variant         (bright cyan)
" 15 on_surface              (bright white)

let g:terminal_color_0  = "{{ colors.surface_container_high.default.hex }}"
let g:terminal_color_1  = "{{ colors.error.default.hex }}"
let g:terminal_color_2  = "{{ colors.primary.default.hex }}"
let g:terminal_color_3  = "{{ colors.tertiary.default.hex }}"
let g:terminal_color_4  = "{{ colors.secondary.default.hex }}"
let g:terminal_color_5  = "{{ colors.primary_fixed.default.hex }}"
let g:terminal_color_6  = "{{ colors.secondary_fixed.default.hex }}"
let g:terminal_color_7  = "{{ colors.on_surface_variant.default.hex }}"
let g:terminal_color_8  = "{{ colors.outline.default.hex }}"
let g:terminal_color_9  = "{{ colors.error_container.default.hex }}"
let g:terminal_color_10 = "{{ colors.primary_container.default.hex }}"
let g:terminal_color_11 = "{{ colors.tertiary_container.default.hex }}"
let g:terminal_color_12 = "{{ colors.secondary_container.default.hex }}"
let g:terminal_color_13 = "{{ colors.inverse_primary.default.hex }}"
let g:terminal_color_14 = "{{ colors.outline_variant.default.hex }}"
let g:terminal_color_15 = "{{ colors.on_surface.default.hex }}"

" ── Base UI ─────────────────────────────────────────────────────────────────
hi Normal        guibg=NONE guifg={{ colors.on_surface.dark.hex }}
hi NormalNC      guibg=NONE guifg={{ colors.on_surface_variant.dark.hex }}
hi NormalFloat   guibg=NONE guifg={{ colors.on_surface.dark.hex }}
hi FloatBorder   guibg=NONE guifg={{ colors.outline.dark.hex }}
hi FloatTitle    guibg=NONE guifg={{ colors.primary.dark.hex }} gui=bold
hi SignColumn    guibg=NONE guifg={{ colors.outline.dark.hex }}
hi EndOfBuffer   guibg=NONE guifg={{ colors.surface_variant.dark.hex }}
hi VertSplit     guibg=NONE guifg={{ colors.outline_variant.dark.hex }}
hi WinSeparator  guibg=NONE guifg={{ colors.outline_variant.dark.hex }}

" ── Status & Tab lines ──────────────────────────────────────────────────────
hi StatusLine    guibg={{ colors.primary.dark.hex }} guifg={{ colors.on_primary.dark.hex }}
hi StatusLineNC  guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_primary_container.dark.hex }}
hi TabLine       guibg=NONE guifg={{ colors.on_surface_variant.dark.hex }}
hi TabLineFill   guibg=NONE guifg={{ colors.outline.dark.hex }}
hi TabLineSel    guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_primary_container.dark.hex }} gui=bold

" ── Line numbers & cursor ────────────────────────────────────────────────────
hi LineNr        guibg=NONE guifg={{ colors.outline.dark.hex }}
hi CursorLineNr  guibg=NONE guifg={{ colors.primary.dark.hex }} gui=bold
hi CursorLine    guibg={{ colors.surface_container_high.dark.hex }} guifg=NONE
hi CursorColumn  guibg={{ colors.surface_container_high.dark.hex }} guifg=NONE
hi ColorColumn   guibg={{ colors.surface_container_highest.dark.hex }} guifg=NONE
hi Cursor        guibg={{ colors.primary.dark.hex }} guifg={{ colors.on_primary.dark.hex }}
hi lCursor       guibg={{ colors.secondary.dark.hex }} guifg={{ colors.on_secondary.dark.hex }}

" ── Folds ───────────────────────────────────────────────────────────────────
hi FoldColumn    guibg=NONE guifg={{ colors.outline.dark.hex }}
hi Folded        guibg=NONE guifg={{ colors.outline_variant.dark.hex }} gui=italic

" ── Search & Selection ──────────────────────────────────────────────────────
hi Search        guibg={{ colors.tertiary_container.dark.hex }} guifg={{ colors.on_tertiary_container.dark.hex }}
hi IncSearch     guibg={{ colors.tertiary.dark.hex }} guifg={{ colors.on_tertiary.dark.hex }}
hi CurSearch     guibg={{ colors.tertiary.dark.hex }} guifg={{ colors.on_tertiary.dark.hex }}
hi Visual        guibg={{ colors.secondary_container.dark.hex }} guifg={{ colors.on_secondary_container.dark.hex }}
hi VisualNOS     guibg={{ colors.secondary_container.dark.hex }} guifg={{ colors.on_secondary_container.dark.hex }}
hi Substitute    guibg={{ colors.error_container.dark.hex }} guifg={{ colors.on_error_container.dark.hex }}

" ── Popup menu ──────────────────────────────────────────────────────────────
hi Pmenu         guibg={{ colors.surface_container.dark.hex }} guifg={{ colors.on_surface.dark.hex }}
hi PmenuSel      guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_primary_container.dark.hex }} gui=bold
hi PmenuSbar     guibg={{ colors.surface_container_high.dark.hex }} guifg=NONE
hi PmenuThumb    guibg={{ colors.outline.dark.hex }} guifg=NONE
hi PmenuBorder   guibg=NONE guifg={{ colors.outline.dark.hex }}
hi PmenuKind     guibg={{ colors.surface_container.dark.hex }} guifg={{ colors.secondary.dark.hex }}
hi PmenuKindSel  guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.secondary.dark.hex }}
hi PmenuExtra    guibg={{ colors.surface_container.dark.hex }} guifg={{ colors.on_surface_variant.dark.hex }}
hi PmenuExtraSel guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_surface_variant.dark.hex }}

" ── Messages & errors ────────────────────────────────────────────────────────
hi Error         guibg={{ colors.error_container.dark.hex }} guifg={{ colors.on_error_container.dark.hex }}
hi ErrorMsg      guibg={{ colors.error_container.dark.hex }} guifg={{ colors.on_error_container.dark.hex }}
hi WarningMsg    guibg=NONE guifg={{ colors.tertiary.dark.hex }}
hi InfoMsg       guibg=NONE guifg={{ colors.secondary.dark.hex }}
hi ModeMsg       guibg=NONE guifg={{ colors.primary.dark.hex }} gui=bold
hi MoreMsg       guibg=NONE guifg={{ colors.primary.dark.hex }}
hi Question      guibg=NONE guifg={{ colors.primary.dark.hex }}

" ── Misc UI ─────────────────────────────────────────────────────────────────
hi NonText       guibg=NONE guifg={{ colors.surface_variant.dark.hex }}
hi SpecialKey    guibg=NONE guifg={{ colors.outline.dark.hex }}
hi Conceal       guibg=NONE guifg={{ colors.outline.dark.hex }}
hi Directory     guibg=NONE guifg={{ colors.secondary.dark.hex }}
hi Title         guibg=NONE guifg={{ colors.primary.dark.hex }} gui=bold
hi WildMenu      guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_primary_container.dark.hex }}
hi MatchParen    guibg={{ colors.tertiary_container.dark.hex }} guifg={{ colors.on_tertiary_container.dark.hex }} gui=bold
hi QuickFixLine  guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_primary_container.dark.hex }}
hi debugPC       guibg={{ colors.secondary_container.dark.hex }} guifg={{ colors.on_secondary_container.dark.hex }}
hi debugBreakpoint guibg={{ colors.error_container.dark.hex }} guifg={{ colors.on_error_container.dark.hex }}

" ── Diffs ───────────────────────────────────────────────────────────────────
hi DiffAdd       guibg={{ colors.tertiary_container.dark.hex }} guifg=NONE
hi DiffChange    guibg={{ colors.secondary_container.dark.hex }} guifg=NONE
hi DiffDelete    guibg={{ colors.error_container.dark.hex }} guifg={{ colors.on_error_container.dark.hex }}
hi DiffText      guibg={{ colors.tertiary.dark.hex }} guifg={{ colors.on_tertiary.dark.hex }}

" ── Spelling ────────────────────────────────────────────────────────────────
hi SpellBad      guibg=NONE guifg={{ colors.error.dark.hex }} gui=undercurl guisp={{ colors.error.dark.hex }}
hi SpellCap      guibg=NONE guifg={{ colors.tertiary.dark.hex }} gui=undercurl guisp={{ colors.tertiary.dark.hex }}
hi SpellRare     guibg=NONE guifg={{ colors.secondary.dark.hex }} gui=undercurl guisp={{ colors.secondary.dark.hex }}
hi SpellLocal    guibg=NONE guifg={{ colors.primary.dark.hex }} gui=undercurl guisp={{ colors.primary.dark.hex }}

" ── Syntax ──────────────────────────────────────────────────────────────────
hi Comment       guibg=NONE guifg={{ base16.base03.dark.hex }} gui=italic
hi Constant      guibg=NONE guifg={{ base16.base09.dark.hex }}
hi String        guibg=NONE guifg={{ base16.base0b.dark.hex }}
hi Character     guibg=NONE guifg={{ base16.base0b.dark.hex }}
hi Number        guibg=NONE guifg={{ base16.base09.dark.hex }}
hi Boolean       guibg=NONE guifg={{ base16.base09.dark.hex }}
hi Float         guibg=NONE guifg={{ base16.base09.dark.hex }}
hi Identifier    guibg=NONE guifg={{ base16.base08.dark.hex }}
hi Function      guibg=NONE guifg={{ base16.base0d.dark.hex }}
hi Statement     guibg=NONE guifg={{ base16.base0e.dark.hex }}
hi Conditional   guibg=NONE guifg={{ base16.base0e.dark.hex }}
hi Repeat        guibg=NONE guifg={{ base16.base0e.dark.hex }}
hi Label         guibg=NONE guifg={{ base16.base0a.dark.hex }}
hi Operator      guibg=NONE guifg={{ base16.base05.dark.hex }}
hi Keyword       guibg=NONE guifg={{ base16.base0e.dark.hex }} gui=bold
hi Exception     guibg=NONE guifg={{ colors.error.dark.hex }}
hi PreProc       guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi Include       guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi Define        guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi Macro         guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi PreCondit     guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi Type          guibg=NONE guifg={{ base16.base0a.dark.hex }}
hi StorageClass  guibg=NONE guifg={{ base16.base0a.dark.hex }}
hi Structure     guibg=NONE guifg={{ base16.base0a.dark.hex }}
hi Typedef       guibg=NONE guifg={{ base16.base0a.dark.hex }}
hi Special       guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi SpecialChar   guibg=NONE guifg={{ base16.base0c.dark.hex }}
hi Tag           guibg=NONE guifg={{ base16.base0d.dark.hex }}
hi Delimiter     guibg=NONE guifg={{ base16.base05.dark.hex }}
hi SpecialComment guibg=NONE guifg={{ base16.base03.dark.hex }} gui=bold
hi Debug         guibg=NONE guifg={{ colors.error.dark.hex }}
hi Underlined    guibg=NONE guifg={{ colors.secondary.dark.hex }} gui=underline
hi Ignore        guibg=NONE guifg={{ colors.surface_variant.dark.hex }}
hi Todo          guibg={{ colors.tertiary_container.dark.hex }} guifg={{ colors.on_tertiary_container.dark.hex }} gui=bold

" ── Treesitter (semantic token) overrides ───────────────────────────────────
hi! link @variable              Identifier
hi! link @variable.builtin      Special
hi! link @variable.parameter    Identifier
hi! link @variable.member       Identifier
hi! link @constant              Constant
hi! link @constant.builtin      Special
hi! link @constant.macro        Define
hi! link @module                Structure
hi! link @module.builtin        Special
hi! link @label                 Label
hi! link @string                String
hi! link @string.documentation  SpecialComment
hi! link @string.regexp         SpecialChar
hi! link @string.escape         SpecialChar
hi! link @string.special        SpecialChar
hi! link @character             Character
hi! link @character.special     SpecialChar
hi! link @boolean               Boolean
hi! link @number                Number
hi! link @number.float          Float
hi! link @type                  Type
hi! link @type.builtin          Special
hi! link @type.definition       Typedef
hi! link @attribute             PreProc
hi! link @property              Identifier
hi! link @function              Function
hi! link @function.builtin      Special
hi! link @function.call         Function
hi! link @function.macro        Macro
hi! link @function.method       Function
hi! link @function.method.call  Function
hi! link @constructor           Function
hi! link @operator              Operator
hi! link @keyword               Keyword
hi! link @keyword.coroutine     Special
hi! link @keyword.function      Keyword
hi! link @keyword.operator      Operator
hi! link @keyword.import        Include
hi! link @keyword.type          Keyword
hi! link @keyword.modifier      Keyword
hi! link @keyword.repeat        Repeat
hi! link @keyword.return        Keyword
hi! link @keyword.debug         Debug
hi! link @keyword.exception     Exception
hi! link @keyword.conditional   Conditional
hi! link @keyword.directive     Define
hi! link @keyword.directive.define Define
hi! link @punctuation.delimiter Delimiter
hi! link @punctuation.bracket   Delimiter
hi! link @punctuation.special   SpecialChar
hi! link @comment               Comment
hi! link @comment.documentation SpecialComment
hi! link @comment.error         Error
hi! link @comment.warning       WarningMsg
hi! link @comment.todo          Todo
hi! link @comment.note          SpecialComment
hi! link @markup.strong         Title
hi! link @markup.italic         Comment
hi! link @markup.strikethrough  Comment
hi! link @markup.underline      Underlined
hi! link @markup.heading        Title
hi! link @markup.quote          Comment
hi! link @markup.math           Special
hi! link @markup.link           Underlined
hi! link @markup.link.label     Title
hi! link @markup.raw            String
hi! link @markup.list           Statement
hi! link @diff.plus             DiffAdd
hi! link @diff.minus            DiffDelete
hi! link @diff.delta            DiffChange
hi! link @tag                   Tag
hi! link @tag.builtin           Special
hi! link @tag.attribute         Identifier
hi! link @tag.delimiter         Delimiter

" ── LSP semantic tokens ──────────────────────────────────────────────────────
hi! link @lsp.type.class         Type
hi! link @lsp.type.comment       Comment
hi! link @lsp.type.decorator     Function
hi! link @lsp.type.enum          Type
hi! link @lsp.type.enumMember   Constant
hi! link @lsp.type.function      Function
hi! link @lsp.type.interface     Type
hi! link @lsp.type.keyword       Keyword
hi! link @lsp.type.macro         Macro
hi! link @lsp.type.method        Function
hi! link @lsp.type.modifier      Keyword
hi! link @lsp.type.namespace     Structure
hi! link @lsp.type.number        Number
hi! link @lsp.type.operator      Operator
hi! link @lsp.type.parameter     Identifier
hi! link @lsp.type.property      Identifier
hi! link @lsp.type.regexp        SpecialChar
hi! link @lsp.type.string        String
hi! link @lsp.type.struct        Structure
hi! link @lsp.type.type          Type
hi! link @lsp.type.typeParameter Typedef
hi! link @lsp.type.variable      Identifier

" ── LSP Diagnostics ─────────────────────────────────────────────────────────
hi DiagnosticError            guibg=NONE guifg={{ colors.error.dark.hex }}
hi DiagnosticWarn             guibg=NONE guifg={{ colors.tertiary.dark.hex }}
hi DiagnosticInfo             guibg=NONE guifg={{ colors.secondary.dark.hex }}
hi DiagnosticHint             guibg=NONE guifg={{ colors.primary.dark.hex }}
hi DiagnosticOk               guibg=NONE guifg={{ colors.tertiary_container.dark.hex }}

hi DiagnosticUnderlineError   guibg=NONE gui=undercurl guisp={{ colors.error.dark.hex }}
hi DiagnosticUnderlineWarn    guibg=NONE gui=undercurl guisp={{ colors.tertiary.dark.hex }}
hi DiagnosticUnderlineInfo    guibg=NONE gui=undercurl guisp={{ colors.secondary.dark.hex }}
hi DiagnosticUnderlineHint    guibg=NONE gui=undercurl guisp={{ colors.primary.dark.hex }}
hi DiagnosticUnderlineOk      guibg=NONE gui=undercurl guisp={{ colors.tertiary_container.dark.hex }}

hi DiagnosticVirtualTextError guibg={{ colors.error_container.dark.hex }} guifg={{ colors.on_error_container.dark.hex }}
hi DiagnosticVirtualTextWarn  guibg={{ colors.tertiary_container.dark.hex }} guifg={{ colors.on_tertiary_container.dark.hex }}
hi DiagnosticVirtualTextInfo  guibg={{ colors.secondary_container.dark.hex }} guifg={{ colors.on_secondary_container.dark.hex }}
hi DiagnosticVirtualTextHint  guibg={{ colors.primary_container.dark.hex }} guifg={{ colors.on_primary_container.dark.hex }}
hi DiagnosticVirtualTextOk    guibg={{ colors.tertiary_container.dark.hex }} guifg={{ colors.on_tertiary_container.dark.hex }}

hi DiagnosticSignError        guibg=NONE guifg={{ colors.error.dark.hex }}
hi DiagnosticSignWarn         guibg=NONE guifg={{ colors.tertiary.dark.hex }}
hi DiagnosticSignInfo         guibg=NONE guifg={{ colors.secondary.dark.hex }}
hi DiagnosticSignHint         guibg=NONE guifg={{ colors.primary.dark.hex }}
hi DiagnosticSignOk           guibg=NONE guifg={{ colors.tertiary_container.dark.hex }}

hi DiagnosticFloatingError    guibg=NONE guifg={{ colors.error.dark.hex }}
hi DiagnosticFloatingWarn     guibg=NONE guifg={{ colors.tertiary.dark.hex }}
hi DiagnosticFloatingInfo     guibg=NONE guifg={{ colors.secondary.dark.hex }}
hi DiagnosticFloatingHint     guibg=NONE guifg={{ colors.primary.dark.hex }}
