general {
  gaps_in = 2
  gaps_out = 4
  border_size = 2
  col.active_border = rgba(333333ee)
  col.inactive_border = rgba(2d2d2dee)
  layout = master
}

decoration {
  rounding = 8
  blur {
    enabled = true
    size = 20
    passes = 5
  }
}
