# --- Main Colors ---
background            #19120c
foreground            #efe0d6
cursor                #efe0d6
cursor_text_color     #19120c

selection_background  #5a422e
selection_foreground  #ffdcc2

url_color             #c4cb97

# --- ANSI Colors ---
color0                #19120c
color1                #ffb4ab
color2                #c4cb97
color3                #e3c0a5
color4                #ffb77a
color5                #c4cb97
color6                #e3c0a5
color7                #efe0d6

color8                #51443b
color9                #93000a
color10               #434a22
color11               #5a422e
color12               #6b3b05
color13               #5a422e
color14               #434a22
color15               #d6c3b6

# --- Starship Prompt Bubbles ---
color255              #6b3b05
color254              #ffb77a
color253              #5a422e
color252              #e3c0a5
color251              #434a22
color250              #c4cb97
color249              #93000a
color248              #ffb4ab

color232              #ffdcc2
color233              #4c2700
color234              #ffdcc2
color235              #412c19
color236              #e0e7b1
color237              #2d330d
color238              #ffdad6
color239              #690005
color240              #ffdcc2

# Matched with unthemed light/dark
color243              #ffb77a
color244              #ffb4ab
color245              #51443b

# --- UI Elements ---
active_tab_foreground   #4c2700
active_tab_background   #ffb77a
inactive_tab_foreground #ffdcc2
inactive_tab_background #6b3b05

active_border_color     #ffb77a
inactive_border_color   #9e8e82

# --- Marks ---
mark1_foreground        #2e1500
mark1_background        #ffdcc2
mark2_foreground        #2a1707
mark2_background        #ffdcc2
mark3_foreground        #191e00
mark3_background        #e0e7b1
