general {
  gaps_in = 2
  gaps_out = 4
  border_size = 2
  col.active_border = rgba(5c5c5cee)
  col.inactive_border = rgba(404040ee)
  layout = master
}

decoration {
  rounding = 8
  blur {
    enabled = true
    size = 20
    passes = 5
  }
}
