general {
  gaps_in = 2
  gaps_out = 4
  border_size = 2
  col.active_border = rgba(83a598ee)
  col.inactive_border = rgba(928374ee)
  layout = master
}

decoration {
  rounding = 6
  blur {
    enabled = true
    size = 20
    passes = 5
    new_optimizations = true
  }
  active_opacity = 1.0
  # inactive_opacity = 0.7
#   shadow {
#     enabled = true
#     range = 20
#     render_power = 3
# }
}
