dwindle {
  # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  preserve_split = true # you probably want this
}

master {
  # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  mfact = 0.5
  new_status = slave
}
