exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = sh -c 'waybar &'
exec-once = dunst
exec-once = awww-daemon
exec-once = awww img "/home/wesii/Pictures/wallpapers/Anime-Girl4.jpeg" --transition-type none


exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hypridle -c ~/.config/hypr/hypridle.conf

 exec-once = qs -d

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1


exec-once = xhost +local:root
