windowrule {  
  name = xwaylandvideobridge-fixes  
  match:class = ^(xwaylandvideobridge)$  

  opacity = 0.0 override 0.0 override  
  no_anim = on  
  no_initial_focus = on  
  no_blur = on  
}

windowrule {
  name = notification-history
  match:class = ^(notifications)$
  float = on
  size = 800 500
  center = on
}

windowrule {
    name = polkit-elevation-fix
    match:class = ^(polkit-gnome-authentication-agent-1)$
    
    float = on
    workspace = cr
}

windowrule {
    name = xdg-portal-gnome-file-chooser
    match:class = ^(xdg-desktop-portal-gnome)$
    
    float = on
    size = 950 600
    center = on
}

windowrule {
    name = xdg-portal-fallback-chooser
    #add any file picker window title here
    match:title = ^(Open File|Save File|Select a Directory|Choose Image|Select one or more files to open|Open Document)$
    
    float = on
    size = 950 600
    center = on
}

windowrule {
   name = center-floating-help-menu
   match:initial_class = ^(hypr_help)$
   float = on
   size = 900 600
   center = on
}

windowrule {
   name =  quick-settings
   match:initial_class = ^(quick-settings)$
   float = on
   size = 900 600
   center = on
}

windowrule {
    name = gnome-calculator
    match:initial_class = ^(org.gnome.Calculator)$
    float = on
    size = 400 500
    center = on
}

windowrule {
    name = frog-ocr
    match:initial_class = ^(com.github.tenderowl.frog)$
    float = on
    center = on
    size = 500 600
}
